apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: construction-service
  template:
    metadata:
      labels:
        app: construction-service
    spec:
      containers:
        - name: construction-service
          image: gcr.io/construction-project-382718/construction-service:44
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: construction-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: construction-service
