apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-service
spec:
  selector:
    matchLabels:
      app: construction-service
  template:
    metadata:
      labels:
        app: construction-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          image: gcr.io/construction-project-382718/construction-service:109
          ports:
            - name: liveness-port
              containerPort: 8080
              hostPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"

          startupProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: construction-service
spec:
  type: LoadBalancer
  selector:
    app: construction-service
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
    - name: http
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Cluster
