apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: construction-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-reader
subjects:
  - kind: ServiceAccount
    name: construction-service
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: construction-service
  template:
    metadata:
      labels:
        app: construction-service
    spec:
      serviceAccountName: construction-service
      containers:
        - name: construction-service
          image: gcr.io/construction-project-382718/construction-service:44
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: construction-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: construction-service
