apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-service
  namespace: deployment
spec:
  selector:
    matchLabels:
      app: construction-service
  template:
    metadata:
      labels:
        app: construction-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          image: gcr.io/construction-project-382718/construction-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: construction-service
  namespace: deployment
spec:
  type: LoadBalancer
  selector:
    app: construction-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: public
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin
  externalTrafficPolicy: Cluster
