spring:
  application:
    name: construction-service
  datasource:
    url: jdbc:postgresql://34.173.138.111:5432/CONSTRUCTION
    username: construction-dev
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true