spring:
  application:
    name: construction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/CONSTRUCTION
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true